version: 2.1

executors:
  node10:
    docker:
      - image: circleci/node:10.21.0-buster
    environment:
      NPM_CONFIG_PREFIX: ~/.npm-global

commands:
  setup:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
      - run:
          name: install latest npm
          command: sudo npm -g install npm
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
      - run:
          name: prepare test git user
          command: git config --global user.email "circleci@example.com" && git config --global user.name "CircleCi Build"

orbs:
    helix-smoke-tests: adobe/helix-smoke-tests@0.0.11

jobs:
  build:
    executor: node10
    steps:
      - setup
      - run: mkdir junit
      - run:
          name: Test and Code Coverage
          command: npm run test-ci
          environment:
            MOCHA_FILE: junit/test-results.xml

      - store_test_results:
          path: junit

      - store_artifacts:
          path: junit

  release:
    executor: node10
    steps:
      - setup
      - run:
          name: revert changes to package-lock.json
          command: git checkout -- package-lock.json

      - run:
          name: Semantic Release
          command: npm run semantic-release

  generate-docs:
    executor: node10
    steps:
      - setup
      - add_ssh_keys:
          fingerprints:
            - "e2:da:a5:eb:5a:3c:69:a8:d7:1a:db:19:26:86:69:2b"
      - run: git checkout -- .
      - run: git pull --rebase origin $CIRCLE_BRANCH
      - run: npm run docs
      - run:
          name: Check if new docs were generated
          command: |
            if [ -z "$(git status --porcelain)" ]; then
              echo "No new docs generated. Halting step."
              circleci-agent step halt
            fi
      - run: git status -s
      - run:
          name: Publish Markdown to GitHub
          command: |
            git add -A docs/ && git commit -m "chore(docs): updating documentation [skip ci]" && git push origin $CIRCLE_BRANCH

workflows:
  version: 2
  build:
    jobs:
    - build
    - release:
        requires:
        - build
        filters:
          branches:
            only: master

    # generate documentation on non-renovate branches
    - generate-docs:
        requires:
        - build
        filters:
          branches:
            ignore:
              - master
              - /renovate\/.*/

  smoke:
    jobs:
    - helix-smoke-tests/run:
        remote_repo: adobe/helix-continuous
